### ISSUE TITLE
Quotation manager

### ISSUE THREAD

**Issue by tanius** [edgeryders/openethnographer#22]
The current implementation proposal (which seems most economical) is to use Drupal taxonomy term pages for displaying all occurences of a tag, incl. text snippets with the tag highlighted with the usual Annotator means (with on-hover popup, but not necessarily an edit / delete function). This list can be created with a special, code-generated view of annotations and the [`taxonomy_display`](https://www.drupal.org/project/taxonomy_display) Drupal module (better than [`tvi`](https://www.drupal.org/project/tvi) for this purpose!). If possible in simple ways (that is, with a third-party module), this list of annotations should also be searchable by words that appear in the same node.

**Comment by danohuiginn** [comment]
I'm going to start work on this now, beginning with the backend plumbing.

We'll need to think more about the UI, but that'll be easier once we have the basic code in place.

**Comment by tanius** [comment]
Drupal taxonomy term pages are frontend pages, so the UI at least goes to the right "end", however it will look like finally. I guess a good deal of the basic coding will revolve around regulating access, based on the terms' new `uid` field and a (not yet there) "public / private tag" field for the terms.

Also for possible re-use cases (like in a future sidebar etc.), it would be cool if the snippet-generation code would allow generic reuse. Since one text snippet with one annotation can be considered the rendering of that annotation, you might want to implement it as "rendering of an entity". Just like "rendering of nodes", which are also Drupal entities. Likewise `annotation` is already a Drupal entity in the code. Or maybe there is a cleaner structure for this still.

**Comment by tanius** [comment]
Just saw that the view operation on annotations is already implemented and needed e.g. when clicking on the chain icon within one annotation's Annotator JS bubble. Links look like `/annotation/123`.

So maybe make "annotation plus snippet" simply a different Drupal display mode of the annotation entity? Just like all the other entities can have different display modes?

**Comment by tanius** [comment]
Even better: no need for two display modes, as the `/annotation/123` type pages to view individual annotations have to be reworked anyway and can shown an annotation just the same way as you would render them into the quotation manager's list on a taxonomy term page.

Just that a `/annotation/123` page shows one, while you can use the `taxonomy_display` Drupal module or a similar mechanism to show multiple ones, form a code-generated Drupal View that lists "rendered entities" of type "annotation".

You might want that  the way to render annotations in this list gets "properly designed" ;) so you could just use a draft rendering for now. For example, on the [Annotator JS website](http://annotatorjs.org/) they render these individual annotation views as little cards ([temp example](http://annotateit.org/annotations/85mkZXVfQsu6CbB8xGBuRQ)).
