### ISSUE TITLE
Showing the author's name in a rendered annotation

### ISSUE THREAD

**Issue by tanius** [edgeryders/openethnographer#31]
Since Open Ethnographer is meant as a multi-user application, the Annotator JS "bubbles" for showing annotations should show the author.

The author might only be shown if it's not  the current user, to limit unnecessary distraction. But that has to be tested.

One way to distinguish annotations of others from own annotations should probably go into the 1.0 release. So either this feature or an alternative one that will affect the text highlight color (yellow for own annotations, gray for others').

**Comment by danohuiginn** [comment]
this already happens, doesn't it? Your first paragraph, at least.

see screenshot. Usernames are 'dan' and 'commie' (eh, don't ask!)

![oeth_user_names](https://cloud.githubusercontent.com/assets/6331/5763703/036da952-9ced-11e4-9b22-245b12e9371f.png)

**Comment by tanius** [comment]
Found it! After I enabled the Permissions plugin at `/admin/config/content/annotator`, author names are shown here as well. Just enabling it, no need to change its plugin config.

I'll put that into the docs. (We need that plugin anyway, it fixes #29.)
