### ISSUE TITLE
Comments of nodes of new content type "Challenge response" are not commentable 

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/openethnographer#55]
@tanius said:

> It will be due to the JQuery selector which finds only regular comments, not those of our new content type "Challenge Response". Does want @danohuiginn  to fix this one?

**Comment by albertocottica** [comment]
I tried looking up the code for "Post" and "jquery", but could not identify a place where to make the fix.

**Comment by danohuiginn** [comment]
@tanius : almost -- but I think it's changing html layout overall, not specifically the challenge response content type

The selector is  a setting at https://edgeryders.eu/en/admin/config/content/annotator (which explains why @albertocottica couldn't find it in the code)

Currently it is .block-content > .node [data-annotator-target*="body/"] 

It seems that with opencare new html, comments are no longer inside the same .block_content div as the main content. So we do need to change the selector a bit.

**Comment by albertocottica** [comment]
Comments to old posts (annotateable): `<div class ="block-content"`
Comments to challenge response (non-annotateable): `<div class = "block-content"> == $0`

Does this make any sense?

**Comment by danohuiginn** [comment]
Fixed (and live, since it only needed a configuration change)

**Comment by albertocottica** [comment]
Yay! Great work.
