### ISSUE TITLE
Create an interface to easily delete annotations

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/openethnographer#58]
Annotations can be deleted from the admin interface: https://edgeryders.eu/en/admin/content/annotation . 

Apparently we had already provided for this, but it not working now. It might come online when we accept and deploy #53 .

**Comment by danohuiginn** [comment]
This is now implemented and live.

The only problem is, it doesn't work immediately after creating an annotation. So if you annotate and immediately realise it was a mistake, you'll need to reload the page before you see the delete button on the annotation.

[that's obviously still a bug, but a slightly less urgent one]
