### ISSUE TITLE
Use multi-substring search in the tagger's auto-completion

### ISSUE THREAD

**Issue by tanius** [edgeryders/openethnographer#6]
Firefox has a pretty elaborate history search function in the address bar, and this kind of search seems also the fastest way for ethnographers to find a tag quickly in a large collection even if not knowing the exact words or spelling in the tag, and without having to use wildcard search syntax or worse.

It works like this: an AND search made up from separate searches for every whitespace-separated substring in the search box. So, given the tag name "house of cardboards project", each of the following will match it:

  * cardboards project
  * house card
  * cardboard house
  * card board project
  * proj cardb

The latter example is how I tend to use Firefox address bar history search: type only the initial letters of some words you remember to appear. It is *fast* :) and once ethnographers get the hang of it, it will speed up their work.

Should not be a big deal to implement as we use client-side search. (But not that important either. And of course it's up for discussion if this proposal makes sense at all.)

**Comment by danohuiginn** [comment]
@tanius, I **love** that you are identifying all these small UI tweaks. Getting details like this right is going to make a huge difference to the overall usefulness of the project.

[that said, I'm going to look at some other stuff before I get to this one]
