### ISSUE TITLE
Codes are broken at spaces [new behaviour]

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/openethnographer#66]
When a code's name includes a space, OE interprets it as two codes. So, typing `my code`in the code field results in the annotation being coded with `my`and `code`. This is new, because in the database we still have things like `existing systems failure`.

**Comment by tanius** [comment]
Unfortunately this issue does not belong here, except you indeed observed it in the _Drupal_ version of OpenEthnographer.

For the Discourse version, please create a new issue [here](https://github.com/edgeryders/discourse/issues).
