### ISSUE TITLE
"There was a problem connecting with the annotation store "

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/openethnographer#67]
Never seen that one before. Open Ethnographer accepted the annotation, but we got the message above. We think the annotations were not saved to the database.

**Comment by tanius** [comment]
Unfortunately this issue does not belong here, except you indeed observed it in the _Drupal_ version of OpenEthnographer.

For the Discourse version, please create a new issue [here](https://github.com/edgeryders/discourse/issues).
